### ISSUE TITLE
Make USAID P2 wide version

### ISSUE THREAD

**Issue by arw36** [ecohealthalliance/ehastyle#4]

**Comment by arw36** [comment]
Got `Error: YAML output format must evaluate to a function
Execution halted` when trying to knit

**Comment by noamross** [comment]
It worked for me in a test doc:
[testaid (1).docx](https://github.com/ecohealthalliance/ehastyle/files/1831803/testaid.1.docx)

Can you post the file you tried to knit?  Note the header should look like this:

```
---
title: "Untitled"
output: ehastyle::usaid
---
```

or

```
title: "Untitled"
output: 
  ehastyle::usaid_word:
    usaid_panel: 2
---
```

Note YAML is is very finicky about indentation and white space.
